### PR TITLE
Rearrange value/precision/units fields

### LINKED ISSUE #57: Rearrange <value> +/- <precision> <units>
It's currently `<value> <units> +/- <precision>` in most places.

### PR DESCRIPTION
**Pull request by skearnes**
Resolves #57

### CODE REVIEW

**Comment by skearnes** [comment]
(TODO: reformat that whole file so it's actually readable...)

**Review by connorcoley — APPROVED** [review]
Before merging, one question. Since most people are unlikely to use the precision field, should we have it hidden by default with the ability to add it? Or is that just going to clutter up the form with an extra link/button?

Perhaps having it always be visible will encourage people to enter it more often than they otherwise would

**Comment by skearnes** [comment]
My preference would be to leave it as-is and hope that more people use it. I'm not opposed to adding a +/- button, for instance, to show/hide the field, but that might cause more people to miss it entirely?

**Comment by connorcoley** [comment]
> My preference would be to leave it as-is 

SGTM

**Pull request merged**
