### PR TITLE
Add a static enumeration template creator.

### LINKED ISSUE #63: Make the process of manually editing a pbtxt for reaction templating more convenient
Ideas:
- Link to some online text editor with a decent monospace font to edit the pbtxt
- Is there a way to make it easy to select a value in a pbtxt for templating?
- (Bad idea) buttons next to each field to flag them as static/variable in an enumeration

### PR DESCRIPTION
**Pull request by antonkast-google**
This adds one web page of static content.

Without any server interaction, you can upload a .pbtxt, click on some fields to replace them with enumeration macros, and download the result.

Maybe it's easier than using a text editor. Persuant to #63.

### CODE REVIEW

**Comment by skearnes** [comment]
This is cool! A couple suggestions:

* Clicking twice should "undo" the replacement.
* Please highlight the replaced fields.
* I get the same variable name for multiple fields that show up in the same level of nesting (e.g. identifiers for multiple components).
* It would probably be easier for users if the variable names were editable...

**Comment by antonkast-google** [comment]
I followed skearnes' excellent suggestions. The enumeration macros are now drawn in red. You can edit their macro names by clicking on them. And if you click to their left they will revert to their original non-macro value from the input .pbtxt.

**Comment by skearnes** [comment]
This looks great Anton! I'd suggest adding some instructions at the top so users know they can revert mistakes and edit the column names. Also some general guidance on making sure the names keep their dollar signs and that they must be unique.

**Comment by skearnes** [comment]
(Resolves #63.)

**Comment by antonkast-google** [comment]
Please take a look. This PR now has instructions at the top, including a how-to graphic. Names are automatically normalized to follow the rules for dollar signs and quotation marks. And in case of an input name collision, the new name gets a counter appended.

**Comment by antonkast-google** [comment]
image

**Review by skearnes — APPROVED** [review]
Thanks! The instructions are great. Just one minor thing: clicking on a name and then clicking away causes it to be updated with e.g. "_2" added as a suffix.

**Comment by antonkast-google** [comment]
> Thanks! The instructions are great. Just one minor thing: clicking on a name and then clicking away causes it to be updated with e.g. "_2" added as a suffix.

That was deliberate. I made the sequence be "X", "X_2", "X_3", "X_4", etc. figuring it would be more user-friendly to add "_1" than "_0".

**Pull request merged**
