### PR TITLE
First pass on editor look & feel updates

### LINKED ISSUE #100: Creating a new (empty) reaction gives 3 validation errors, but the bulleted list isn't legible

### PR DESCRIPTION
**Pull request by skearnes**
See https://docs.google.com/document/d/1IvNBW7BmG8-8byLFP8WGvwBAOol5DC2nA6xIBQxoelo/edit#

### CODE REVIEW

**Comment by connorcoley** [comment]
Thanks for already addressing so many items on that list. This is a definite step in the right direction.

I would propose that we continue to work off of your branch to finish out a larger set of aesthetic changes before merging, rather than doing them piecemeal. That way, if we need to update the videos or any documentation, there will be one abrupt change rather than a prolonged gradual one. Is that okay with you?

**Comment by skearnes** [comment]
> I would propose that we continue to work off of your branch to finish out a larger set of aesthetic changes before merging, rather than doing them piecemeal. That way, if we need to update the videos or any documentation, there will be one abrupt change rather than a prolonged gradual one. Is that okay with you?

Yes, that sounds great. Thanks!

**Comment by connorcoley** [comment]
I'm still getting weird JS errors from this branch that I haven't been able to resolve yet. Would someone else mind trying a fresh build + deploy (@antonkast-google, @brilee)?

image

(The autosave button fails to load, which is the most obvious indication something is wonky)

**Comment by antonkast-google** [comment]
I tried to debug this, but I'm afraid I'm out of date with our build procedure. When I pull skearnes/look, set all my old environment variables, and build and bring up docker,

docker build -t openreactiondatabase/ord-editor .
docker-compose up

loading localhost:5000 shows a schema problem:

db_1   | 2021-04-24 16:13:31.443 UTC [34] ERROR:  column "name" does not exist at character 8
db_1   | 2021-04-24 16:13:31.443 UTC [34] STATEMENT:  SELECT name FROM datasets WHERE user_id='f2642e52c53b4f54a4749a4

Could this be some legacy schema persisting somewhere in my file system? Or is there a setup step I don't know about or forgot?

**Comment by skearnes** [comment]
@antonkast-google that's because your local database is out of date. If you blow away `~/ord-editor-data` or wherever that lives and rebuild it should work.

**Comment by antonkast-google** [comment]
Thanks! Almost there.

  db_1   | 2021-04-24 19:56:40.299 UTC [76] FATAL:  database "editor" does not exist

According to my notes, I used to run this manually:

  psql -p 5432 -h localhost -U postgres -f schema.sql

But now I see schema.sql in a Dockerfile so am I missing a step?

**Comment by antonkast-google** [comment]
I went ahead and ran schema.sql manually, so my editor is running.

Right away I hit the following. It looks like we have jQuery reference inlined in HTML, which means it's evaluating before the jQuery script loads at the end of the page.

image

**Comment by skearnes** [comment]
Yes, that's my fault; I'll update the script placement to fix that error.

**Comment by connorcoley** [comment]
Most recent version built well for me; not seeing any issues. Thanks, @skearnes !

**Review by connorcoley — DISMISSED** [review]
LGTM. I wouldn't mind if someone else wanted to do a few more tests though

**Comment by connorcoley** [comment]
- [x] When looking at a dataset or reaction page, the user information in the upper-right corner is lost depending on the window width
- [x] "programmatic interface" link on the homepage under the "Enumerate" tab is missing a space after the link
- [x] When a reaction is loaded with a volume field, the "volume includes solutes" text is not shown. However, it is correctly shown onchange
- [x] The boolean selector for "includes solutes" isn't aligned pixel-perfect, but that's okay probably
- [x] The cancel button on Ketcher doesn't work (i.e., doesn't leave the drawing)
- [x] The "Done drawing" button on Ketcher adds the identifier but doesn't close/hide the window
- [x] Specification of the automation platform does not seem to be saved
- [x] Nitpicky, but can we change the "add pressure" button to "add pressure conditions"? Likewise for electrochemistry and flow. Having the slightly longer field will help them stand out from "add measurement". Making these longer might cause them to run onto multiple lines when loading a blank reaction, however.


And now something subjective: Does it make sense to have some sort of type hierarchy for the add buttons? i.e., "add outcome" adds a top-level field, whereas "add measurement" is a low-level field. Should we make the buttons that correspond to the common major fields a little bigger?

**Comment by skearnes** [comment]
Thanks, fixed all of those issues.

As for the button sizes, I think that's a good idea. I'll play around with something simple like a two-level hierarchy for top-level and others.

**Comment by skearnes** [comment]
PTAL

**Review by connorcoley — APPROVED** [review]
LGTM. Would still appreciate a skim from @michaelmaser and/or @brilee but you've fixed all the bugs I caught. I do like the button changes, too!

**Comment by brilee** [comment]
Currently on vacation - I'll have some time to look at this on Sunday?

**Comment by michaelmaser** [comment]
Overall huge LGTM from me. Some minor things:

Before adding text to a field, the cursor tends to hang over the box dims. Goes away once you start typing:

Screen Shot 2021-05-20 at 7 16 49 AM

When you select to draw a compound, it adds an additional empty identifier field along with the Ketcher MolBlock:
 
Screen Shot 2021-05-20 at 7 19 05 AM

This doesn't happen if you add the SMILES directly:

Screen Shot 2021-05-20 at 7 20 19 AM

Some fields such as electrochemistry and illumination conditions can't be collapsed once opened:

Screen Shot 2021-05-20 at 7 23 23 AM

Many other things, such as observations and vessel attachments can by use of the trash button:

Screen Shot 2021-05-20 at 7 25 44 AM

This results more from the schema, but I worry it will be a bit confusing to have the "keep phase" and "aliquot amount" fields available for a workup of type addition (we might have talked about this already):

Screen Shot 2021-05-20 at 7 26 23 AM

Similar, as a result of using the ReactionInput message for workup inputs, fields like addition order are available. Do we expect that people will keep track of addition order from the reaction setup through the workup, that the workup will start over from 1, or that this field should be unused? The "?" icon here is the same as in the reaction inputs, saying to start from 1:

Screen Shot 2021-05-20 at 7 27 43 AM

It might be nice to have some sort of "complete reaction" button at the very end after this:

Screen Shot 2021-05-20 at 7 32 13 AM

This ended up going away, just wanted to make you aware of it. Had a momentary freeze where I had fixed the validation errors by removing the internal standard and setting the type, but the errors wouldn't go away and the download, save, and validate buttons weren't responding. Had to reload the page and ended up losing the work in this section. Once reloaded, with the proper entry the validation was fine and I could save and download:

Screen Shot 2021-05-20 at 7 37 05 AM

Sorry for the saga, hope this helps!

**Review by michaelmaser — APPROVED** [review]

**Comment by brilee** [comment]
@skearnes I don't think you should block on my review - I'd say let's push it out. I'm most of the way done with the  electrochemistry dataset and I can test out the new UI a whirl on the live editor.

**Comment by skearnes** [comment]
> Overall huge LGTM from me. Some minor things:
> 
> Before adding text to a field, the cursor tends to hang over the box dims. Goes away once you start typing:

Interesting. I don't see this in chrome, but I'll file an issue for later (https://github.com/open-reaction-database/ord-interface/issues/46).
> 
> When you select to draw a compound, it adds an additional empty identifier field along with the Ketcher MolBlock:
> 
> This doesn't happen if you add the SMILES directly:

I don't see this behavior in chrome, either, which seems very strange (https://github.com/open-reaction-database/ord-interface/issues/45).
> 
> Some fields such as electrochemistry and illumination conditions can't be collapsed once opened:
> 
> Many other things, such as observations and vessel attachments can by use of the trash button:
> 

This was somewhat intentional to avoid adding more buttons. Note that there are no collapsible fields anymore in the form, so this would be more of a "remove section" button if we decided to add something here (while the trash cans all refer to removing entries from repeated/map fields rather than scalar sections).

> This results more from the schema, but I worry it will be a bit confusing to have the "keep phase" and "aliquot amount" fields available for a workup of type addition (we might have talked about this already):
> 

Good point; added auto-hide/show functions here like we do with `ProductMeasurement`s. Additionally, I found that the TemperatureConditions and StirringConditions in workups were not reusing any code from the Conditions section, so I fixed that as well.

> Similar, as a result of using the ReactionInput message for workup inputs, fields like addition order are available. Do we expect that people will keep track of addition order from the reaction setup through the workup, that the workup will start over from 1, or that this field should be unused? The "?" icon here is the same as in the reaction inputs, saying to start from 1:
>

Good point; I've automatically hidden these fields in the form.
 
> It might be nice to have some sort of "complete reaction" button at the very end after this:
> 

I decided not to do this because I don't want to automatically move back to the dataset in case there are non-validating fields that might be lost.

> This ended up going away, just wanted to make you aware of it. Had a momentary freeze where I had fixed the validation errors by removing the internal standard and setting the type, but the errors wouldn't go away and the download, save, and validate buttons weren't responding. Had to reload the page and ended up losing the work in this section. Once reloaded, with the proper entry the validation was fine and I could save and download:

Thanks; let's keep an eye out for this in the future.
> 
> Sorry for the saga, hope this helps!

**Comment by skearnes** [comment]
@connorcoley one final look before I merge? I changed a lot of code with the temperature/stirring refactor for workups.

**Comment by connorcoley** [comment]
Comments on new changes:
- Dynamic workup fields are great. However, WAIT and STIRRING is confusing: WAIT has a duration and stirring, but STIRRING doesn't have a duration. I think STIRRING should have a duration. Arguably, WAIT should _just_ be a duration, but also having stirring is okay. 
- The "details" field is kind of small relative to what level of detail would actually be useful in workups. Could this be either a longer single-line field or a paragraph box?


I mostly checked how the interface changes, but also made sure fields were properly saved in a couple of cases.

LGTM other than these two nitpicky things!

**Comment by skearnes** [comment]
> Comments on new changes:
> 
> * Dynamic workup fields are great. However, WAIT and STIRRING is confusing: WAIT has a duration and stirring, but STIRRING doesn't have a duration. I think STIRRING should have a duration. Arguably, WAIT should _just_ be a duration, but also having stirring is okay.

Added duration to STIRRING and removed stirring from WAIT.

> * The "details" field is kind of small relative to what level of detail would actually be useful in workups. Could this be either a longer single-line field or a paragraph box?

Expanded this to a box.
> 
> I mostly checked how the interface changes, but also made sure fields were properly saved in a couple of cases.
> 
> LGTM other than these two nitpicky things!

Thanks!

**Pull request merged**
